# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\":\n\x17\x41uthenticateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"+\n\x18\x41uthenticateUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x14\n\x12StudentDataRequest\"\xe2\x01\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tgender_id\x18\x03 \x01(\t\x12\x10\n\x08\x62irthday\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\r\n\x05phone\x18\x06 \x01(\t\x12\x10\n\x08state_id\x18\x07 \x01(\t\x12\x0c\n\x04\x63ity\x18\x08 \x01(\t\x12\x14\n\x0cneighborhood\x18\t \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\n \x01(\t\x12\x0e\n\x06number\x18\x0b \x01(\t\x12\x0f\n\x07plan_id\x18\x0c \x01(\x05\x12\x12\n\npayment_id\x18\r \x01(\x05\"0\n\x13StudentDataResponse\x12\x19\n\x07student\x18\x01 \x03(\x0b\x32\x08.Student\"\x13\n\x11StatesDataRequest\"7\n\x05State\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x62\x62reviation\x18\x03 \x01(\t\"+\n\x12StatesDataResponse\x12\x15\n\x05state\x18\x01 \x03(\x0b\x32\x06.State\"\x14\n\x12GendersDataRequest\"\"\n\x06Gender\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\".\n\x13GendersDataResponse\x12\x17\n\x06gender\x18\x01 \x03(\x0b\x32\x07.Gender2V\n\x0b\x41uthService\x12G\n\x10\x41uthenticateUser\x12\x18.AuthenticateUserRequest\x1a\x19.AuthenticateUserResponse2M\n\x0eStudentService\x12;\n\x0eGetStudentData\x12\x13.StudentDataRequest\x1a\x14.StudentDataResponse2G\n\x0cStateService\x12\x37\n\x0cGetStateData\x12\x12.StatesDataRequest\x1a\x13.StatesDataResponse2K\n\rGenderService\x12:\n\rGetGenderData\x12\x13.GendersDataRequest\x1a\x14.GendersDataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHENTICATEUSERREQUEST']._serialized_start=17
  _globals['_AUTHENTICATEUSERREQUEST']._serialized_end=75
  _globals['_AUTHENTICATEUSERRESPONSE']._serialized_start=77
  _globals['_AUTHENTICATEUSERRESPONSE']._serialized_end=120
  _globals['_STUDENTDATAREQUEST']._serialized_start=122
  _globals['_STUDENTDATAREQUEST']._serialized_end=142
  _globals['_STUDENT']._serialized_start=145
  _globals['_STUDENT']._serialized_end=371
  _globals['_STUDENTDATARESPONSE']._serialized_start=373
  _globals['_STUDENTDATARESPONSE']._serialized_end=421
  _globals['_STATESDATAREQUEST']._serialized_start=423
  _globals['_STATESDATAREQUEST']._serialized_end=442
  _globals['_STATE']._serialized_start=444
  _globals['_STATE']._serialized_end=499
  _globals['_STATESDATARESPONSE']._serialized_start=501
  _globals['_STATESDATARESPONSE']._serialized_end=544
  _globals['_GENDERSDATAREQUEST']._serialized_start=546
  _globals['_GENDERSDATAREQUEST']._serialized_end=566
  _globals['_GENDER']._serialized_start=568
  _globals['_GENDER']._serialized_end=602
  _globals['_GENDERSDATARESPONSE']._serialized_start=604
  _globals['_GENDERSDATARESPONSE']._serialized_end=650
  _globals['_AUTHSERVICE']._serialized_start=652
  _globals['_AUTHSERVICE']._serialized_end=738
  _globals['_STUDENTSERVICE']._serialized_start=740
  _globals['_STUDENTSERVICE']._serialized_end=817
  _globals['_STATESERVICE']._serialized_start=819
  _globals['_STATESERVICE']._serialized_end=890
  _globals['_GENDERSERVICE']._serialized_start=892
  _globals['_GENDERSERVICE']._serialized_end=967
# @@protoc_insertion_point(module_scope)
